"""Build the Arabic (ar.html) and Chinese (zh.html) pages from index.html.

Run from the allgood-website folder:  python3 tools/translate.py

index.html (English) is the source. Every visible text and every alt /
aria-label / title / description is looked up in the dictionaries below.
If you change English text, add its translation here and run the script
again; it stops and lists any text that has no translation yet.
"""
import html
import re
import sys

AR = {
    "ALL GOOD Power Construction | Industrial Supply & Engineering Services, Saudi Arabia": "ALL GOOD لإنشاءات الطاقة | توريد صناعي وخدمات هندسية، المملكة العربية السعودية",
    "ALL GOOD": "ALL GOOD",
    "Power Construction": "لإنشاءات الطاقة",
    "About": "من نحن",
    "Services": "خدماتنا",
    "Projects": "المشاريع",
    "Partners": "الشركاء",
    "Team": "الفريق",
    "EN": "EN",
    "Contact us": "تواصل معنا",
    "Riyadh · Dammam · Jeddah": "الرياض · الدمام · جدة",
    "Industrial supply &": "توريد صناعي",
    "engineering services": "وخدمات هندسية",
    "Materials, fabrication, construction and equipment for industrial, petrochemical, power and infrastructure projects, from one partner.": "مواد وتصنيع وإنشاء ومعدات للمشاريع الصناعية والبتروكيماوية ومشاريع الطاقة والبنية التحتية، من شريك واحد.",
    "Request a quote": "اطلب عرض سعر",
    "Our services": "خدماتنا",
    "Years in Saudi Arabia": "عامًا في المملكة",
    "Operating bases": "قواعد تشغيل",
    "Benchmark projects": "مشاريع مرجعية",
    "Client response": "استجابة للعملاء",
    "About us": "من نحن",
    "Rooted in Saudi Arabia, working with world-class contractors": "متجذرون في المملكة، ونعمل مع كبار المقاولين العالميين",
    "ALL GOOD Power Construction is an industrial trading and engineering service group headquartered in Riyadh. We supply materials, build on site, and rent and maintain equipment for large energy and infrastructure projects, with our own transport fleet and bases in Riyadh, Dammam and Jeddah.": "ALL GOOD لإنشاءات الطاقة مجموعة للتجارة الصناعية والخدمات الهندسية مقرها الرياض. نورّد المواد وننفذ الأعمال في المواقع ونؤجر المعدات ونصونها لمشاريع الطاقة والبنية التحتية الكبرى، بأسطول نقل خاص بنا وقواعد في الرياض والدمام وجدة.",
    "Mission": "رسالتنا",
    "Long-term partnerships with world-class EPC contractors, supporting Saudi Arabia's energy and infrastructure development.": "شراكات طويلة الأمد مع كبار مقاولي الهندسة والتوريد والإنشاء (EPC) في العالم، دعمًا لتطوير قطاعي الطاقة والبنية التحتية في المملكة.",
    "Vision": "رؤيتنا",
    "To be the most trusted industrial trading and engineering service group in the Middle East, taking part in Saudi Vision 2030.": "أن نكون مجموعة التجارة الصناعية والخدمات الهندسية الأكثر ثقة في الشرق الأوسط، وشريكًا فاعلًا في رؤية السعودية 2030.",
    "Integrity": "النزاهة",
    "Excellence": "التميز",
    "Innovation": "الابتكار",
    "Win-Win": "المنفعة المتبادلة",
    "What we do": "ماذا نقدم",
    "Our five business units": "وحدات أعمالنا الخمس",
    "Everything a project needs, from one partner.": "كل ما يحتاجه المشروع، من شريك واحد.",
    "Unit 01": "الوحدة 01",
    "Unit 02": "الوحدة 02",
    "Unit 03": "الوحدة 03",
    "Unit 04": "الوحدة 04",
    "Unit 05": "الوحدة 05",
    "Electrical materials": "المواد الكهربائية",
    "Exclusive agent of Bahra Electric, Saudi Arabia's largest local cable manufacturer. SEC-compliant.": "الوكيل الحصري لشركة بحرة للكابلات، أكبر مصنّع محلي للكابلات في المملكة. مطابقة لمعايير الشركة السعودية للكهرباء.",
    "Power & control cables": "كابلات القوى والتحكم",
    "Cable trays & conduits": "حوامل الكابلات والمواسير",
    "Switchgear & distribution": "لوحات المفاتيح والتوزيع",
    "Lighting & wiring devices": "الإنارة وملحقات التمديدات",
    "Instrumentation": "أجهزة القياس والتحكم",
    "Communication & fiber optic": "الاتصالات والألياف البصرية",
    "Steel & metal fabrication": "الهياكل الفولاذية والتصنيع المعدني",
    "In-house fabrication for oil, chemical and power plants, to ASME, ASTM, DIN and GB standards.": "تصنيع داخلي لمحطات النفط والكيماويات والطاقة، وفق معايير ASME وASTM وDIN وGB.",
    "Pipes, flanges & fittings": "الأنابيب والفلنجات والتوصيلات",
    "Industrial valves": "الصمامات الصناعية",
    "Steel structures": "الهياكل الفولاذية",
    "Fasteners & stud bolts": "المثبتات ومسامير الربط",
    "Embedded parts & anchor bolts": "القطع المدمجة ومسامير التثبيت",
    "Gaskets, plates & bars": "الحشوات والألواح والقضبان",
    "Engineering construction": "الإنشاءات الهندسية",
    "Professional site crews working to international standards, with a zero safety incident record.": "فرق ميدانية محترفة تعمل وفق المعايير الدولية، بسجل خالٍ من حوادث السلامة.",
    "Waterproofing": "العزل المائي",
    "Anti-corrosion & insulation": "مقاومة التآكل والعزل",
    "Scaffolding": "السقالات",
    "Pipeline installation": "تركيب خطوط الأنابيب",
    "Temporary camps": "المخيمات المؤقتة",
    "Building materials": "مواد البناء",
    "Equipment & site support": "المعدات ودعم المواقع",
    "Agent for Cummins generators, Stamford alternators and Deep Sea controllers. Rental, maintenance and 24-hour response across the Kingdom.": "وكيل لمولدات Cummins ومولدات التيار المتردد Stamford ووحدات التحكم Deep Sea. تأجير وصيانة واستجابة على مدار الساعة في أنحاء المملكة.",
    "Earth moving equipment": "معدات تحريك التربة",
    "Cranes & man lifts": "الرافعات ومنصات العمل المرتفعة",
    "Generators": "المولدات",
    "Welding equipment": "معدات اللحام",
    "Trucks & trailers": "الشاحنات والمقطورات",
    "24/7 emergency response": "استجابة طارئة على مدار الساعة",
    "Local manufacturing": "التصنيع المحلي",
    "Coming soon": "قريبًا",
    "An automated cable tray factory supporting Saudi Vision 2030 and IKTVA local content. With Bahra Electric, one supplier for cable and tray.": "مصنع آلي لحوامل الكابلات يدعم رؤية السعودية 2030 وبرنامج اكتفاء للمحتوى المحلي. ومع بحرة للكابلات، مورّد واحد للكابل والحامل معًا.",
    "Trough & perforated trays": "حوامل مصمتة ومثقبة",
    "Ladder & wide-span trays": "حوامل سلّمية وواسعة البحر",
    "Hot-dip galvanized steel": "فولاذ مجلفن بالغمس الساخن",
    "Stainless steel & aluminum": "فولاذ مقاوم للصدأ وألمنيوم",
    "Selected projects": "مشاريع مختارة",
    "Wind power": "طاقة الرياح",
    "Solar power": "الطاقة الشمسية",
    "Power plant": "محطة كهرباء",
    "Gas turbine": "توربينات غازية",
    "Giga-project": "مشروع عملاق",
    "Turaif Wind Power Project": "مشروع طريف لطاقة الرياح",
    "Saidawi Solar Power Project": "مشروع صيداوي للطاقة الشمسية",
    "Riyadh Qassim CCGT": "محطة الرياض القصيم للدورة المركبة",
    "Wadi Solar Power Project": "مشروع وادي للطاقة الشمسية",
    "PP12 Gas Turbine": "محطة PP12 للتوربينات الغازية",
    "Full HV/LV cable supply for PowerChina. On-time grid connection.": "توريد كامل لكابلات الجهد العالي والمنخفض لشركة PowerChina. ربط بالشبكة في الموعد.",
    "Complete cable and cable tray system for Energy China.": "منظومة كاملة من الكابلات وحواملها لشركة Energy China.",
    "Steel structures, pipes and flanges for PowerChina.": "هياكل فولاذية وأنابيب وفلنجات لشركة PowerChina.",
    "Complete steel structure package for Shandong Electric.": "حزمة هياكل فولاذية كاملة لشركة Shandong Electric.",
    "View details": "عرض التفاصيل",
    "Trusted by contractors, partners and the industry": "ثقة المقاولين والشركاء والقطاع",
    "EPC partners": "شركاء EPC",
    "Brand agencies": "الوكالات التجارية",
    "Standards": "المعايير",
    "Meet the team": "تعرّف على فريقنا",
    "The people behind your project": "الفريق الذي يقف خلف مشروعك",
    "Yu Peng Peng": "Yu Peng Peng",
    "Business contact": "مسؤول تطوير الأعمال",
    "Quotations, supply enquiries, equipment rental and project partnerships.": "عروض الأسعار واستفسارات التوريد وتأجير المعدات وشراكات المشاريع.",
    "Team member name": "اسم عضو الفريق",
    "Position": "المنصب",
    "Short biography: this person's background, experience and what they handle for clients.": "نبذة قصيرة: الخلفية والخبرة وما يتولاه للعملاء.",
    "Contact": "تواصل معنا",
    "Let's talk about your project": "لنتحدث عن مشروعك",
    "Phone": "الهاتف",
    "WhatsApp": "واتساب",
    "WeChat": "ويتشات",
    "WeChat ID": "معرّف ويتشات",
    "Email": "البريد الإلكتروني",
    "info@allgoodpower.com": "info@allgoodpower.com",
    "name@allgoodpower.com": "name@allgoodpower.com",
    "Head office": "المقر الرئيسي",
    "Riyadh, Kingdom of Saudi Arabia": "الرياض، المملكة العربية السعودية",
    "Bases": "القواعد",
    "Dammam · Jeddah": "الدمام · جدة",
    "Scan with WeChat to add us.": "امسح الرمز عبر ويتشات لإضافتنا.",
    "Riyadh (head office)": "الرياض (المقر الرئيسي)",
    "Dammam": "الدمام",
    "Jeddah": "جدة",
    "Project site": "موقع المشروع",
    "Order deliveries": "تسليم الطلبيات",
    "Location": "الموقع",
    "EPC": "مقاول EPC",
    "Client / EPC": "العميل / مقاول EPC",
    "Business unit": "وحدة الأعمال",
    "Result": "النتيجة",
    "Turaif, Saudi Arabia": "طريف، المملكة العربية السعودية",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Riyadh & Qassim, Saudi Arabia": "الرياض والقصيم، المملكة العربية السعودية",
    "Qiddiya, Riyadh, Saudi Arabia": "القدية، الرياض، المملكة العربية السعودية",
    "PowerChina: Shandong Electric Power Construction Corp. No.3": "PowerChina: شركة Shandong Electric Power Construction Corp. No.3",
    "Energy China: Hunan Electric Power Construction Co., Ltd.": "Energy China: شركة Hunan Electric Power Construction",
    "PowerChina": "PowerChina",
    "Shandong Electric Power Construction Group": "مجموعة Shandong Electric Power Construction",
    "Full supply of HV and LV wind power cables, compliant with SEC standards.": "توريد كامل لكابلات الجهد العالي والمنخفض لمشروع طاقة الرياح، مطابقة لمعايير الشركة السعودية للكهرباء.",
    "On-time grid connection, with quality certified by the contractor.": "ربط بالشبكة في الموعد المحدد، بجودة معتمدة من المقاول.",
    "Full cable and cable tray system, in trough and ladder types.": "منظومة كاملة من الكابلات وحواملها بنوعيها المصمت والسلّمي.",
    "One integrated cable-and-tray package; ALL GOOD became a strategic supplier for Energy China.": "حزمة متكاملة للكابلات وحواملها، وأصبحت ALL GOOD موردًا استراتيجيًا لشركة Energy China.",
    "Bulk supply of steel structural components for large gas turbine power plants: pipes, flanges and a full steel package.": "توريد كميات كبيرة من مكونات الهياكل الفولاذية لمحطات التوربينات الغازية الكبرى: أنابيب وفلنجات وحزمة فولاذية كاملة.",
    "Delivered to a strict schedule and quality standard, leading to a long-term strategic partnership.": "تسليم وفق جدول زمني ومعايير جودة صارمة، أسفر عن شراكة استراتيجية طويلة الأمد.",
    "Complete steel structure, plus the full series of flanges, pipe fittings, fasteners and embedded parts.": "هيكل فولاذي كامل، إضافة إلى السلسلة الكاملة من الفلنجات وتوصيلات الأنابيب والمثبتات والقطع المدمجة.",
    "Full compliance with international quality standards and smooth project completion.": "امتثال كامل لمعايير الجودة الدولية وإنجاز سلس للمشروع.",
    "Expansion of the project camp: prefabricated buildings and steel structures for the cafeteria, activity room and staff dormitories.": "توسعة مخيم المشروع: مبانٍ مسبقة الصنع وهياكل فولاذية للمقصف وقاعة الأنشطة وسكن العاملين.",
    "ALL GOOD Power Construction · Riyadh, Kingdom of Saudi Arabia": "ALL GOOD لإنشاءات الطاقة · الرياض، المملكة العربية السعودية",
    "ALL GOOD Power Construction is an industrial trading and engineering service group headquartered in Riyadh, supplying cables, steel structures, equipment and construction services to energy and infrastructure projects across Saudi Arabia.": "ALL GOOD لإنشاءات الطاقة مجموعة للتجارة الصناعية والخدمات الهندسية مقرها الرياض، تورّد الكابلات والهياكل الفولاذية والمعدات وخدمات الإنشاء لمشاريع الطاقة والبنية التحتية في أنحاء المملكة.",
    "ALL GOOD Power Construction home": "الصفحة الرئيسية لALL GOOD",
    "Open menu": "فتح القائمة",
    "Language": "اللغة",
    "The ALL GOOD team": "فريق ALL GOOD",
    "Previous photo": "الصورة السابقة",
    "Next photo": "الصورة التالية",
    "Previous project": "المشروع السابق",
    "Next project": "المشروع التالي",
    "Energy China": "Energy China",
    "Shandong Electric Power Construction Corp. No.3": "Shandong Electric Power Construction Corp. No.3",
    "Hunan Electric Power Construction": "Hunan Electric Power Construction",
    "Bahra Electric": "بحرة للكابلات",
    "Cummins": "Cummins",
    "Stamford": "Stamford",
    "Deep Sea": "Deep Sea",
    "Saudi Electricity Company (SEC)": "الشركة السعودية للكهرباء",
    "Saudi Aramco": "أرامكو السعودية",
    "SABIC": "سابك",
    "ISO": "ISO",
    "ASME": "ASME",
    "ASTM": "ASTM",
    "Call Yu Peng Peng": "اتصل بـ Yu Peng Peng",
    "WeChat QR code": "رمز ويتشات",
    "ALL GOOD head office on Google Maps": "مقر ALL GOOD على خرائط Google",
    "Business units": "وحدات الأعمال",
    "Camp expansion built on site, with our own steel materials.": "توسعة المخيم نُفّذت في الموقع، بموادنا الفولاذية الخاصة.",
    "Engineering construction · Steel & metal fabrication": "الإنشاءات الهندسية · الهياكل الفولاذية والتصنيع المعدني",
    "Full-range steel structure materials for the camp buildings, compliant with ASME and ASTM standards.": "مواد هياكل فولاذية متكاملة لمباني المخيم، مطابقة لمعايير ASME وASTM.",
    "Our role": "دورنا",
    "Our works on site": "أعمالنا في الموقع",
    "Scope as supplier": "النطاق كمورّد",
    "Supplier": "مورّد",
    "We source, deliver and hand over materials and equipment to the project's contractors.": "نوفّر المواد والمعدات ونوصلها ونسلّمها لمقاولي المشروع.",
    "@works-photos": "{x}: صور أعمالنا في الموقع",
    "@works-photo": "{x}: أعمالنا في الموقع، صورة {n}",
    "Client": "العميل",
    "Qiddiya Delta B Office": "مكتب القدية دلتا B",
    "Qiddiya Delta B Office: architectural rendering": "مكتب القدية دلتا B: تصور معماري",
    "Qiddiya Delta B office, architectural rendering": "مكتب القدية دلتا B، تصور معماري",
    "Qiddiya Investment Company (QIC)": "شركة القدية للاستثمار",
    "Turnkey steel-structure office for 200 staff: design, build and operate.": "مبنى مكاتب بهيكل فولاذي لـ 200 موظف بنظام تسليم المفتاح: تصميم وتنفيذ وتشغيل.",
    "As a supplier, as a contractor on site, and on some projects both.": "كمورّد، أو كمقاول في الموقع، وفي بعض المشاريع بالدورين معًا.",
    "Contractor": "مقاول",
    "Contractor & Supplier": "مقاول ومورّد",
    "Scope as contractor": "النطاق كمقاول",
    "Our own crews carry out works inside the project, as main contractor or subcontractor: construction, installation and site services.": "تنفّذ فرقنا الأعمال داخل المشروع، كمقاول رئيسي أو مقاول باطن: الإنشاء والتركيب وخدمات الموقع.",
    "Turnkey design, construction and operation of a 200-staff steel-structure office.": "تصميم وتنفيذ وتشغيل مبنى مكاتب بهيكل فولاذي لـ 200 موظف بنظام تسليم المفتاح.",
    "Close": "إغلاق",
    # pieces used to build image descriptions
    "@photos": "{x}: صور",
    "@photo": "{x}: صورة {n}",
    "@site-photos": "{x}: صور موقع المشروع",
    "@site-photo": "{x}: موقع المشروع، صورة {n}",
    "@delivery-photos": "{x}: صور تسليم الطلبيات",
    "@delivery-photo": "{x}: تسليم الطلبية، صورة {n}",
}

ZH = {
    "ALL GOOD Power Construction | Industrial Supply & Engineering Services, Saudi Arabia": "ALL GOOD 电力建设 | 工业供应与工程服务 · 沙特阿拉伯",
    "ALL GOOD": "ALL GOOD",
    "Power Construction": "电力建设",
    "About": "关于我们",
    "Services": "业务",
    "Projects": "项目",
    "Partners": "合作伙伴",
    "Team": "团队",
    "EN": "EN",
    "Contact us": "联系我们",
    "Riyadh · Dammam · Jeddah": "利雅得 · 达曼 · 吉达",
    "Industrial supply &": "工业供应与",
    "engineering services": "工程服务",
    "Materials, fabrication, construction and equipment for industrial, petrochemical, power and infrastructure projects, from one partner.": "为工业、石化、电力和基础设施项目提供材料、加工、施工与设备，一站式合作伙伴。",
    "Request a quote": "获取报价",
    "Our services": "我们的业务",
    "Years in Saudi Arabia": "深耕沙特年数",
    "Operating bases": "运营基地",
    "Benchmark projects": "标杆项目",
    "Client response": "客户响应",
    "About us": "关于我们",
    "Rooted in Saudi Arabia, working with world-class contractors": "扎根沙特，携手世界一流承包商",
    "ALL GOOD Power Construction is an industrial trading and engineering service group headquartered in Riyadh. We supply materials, build on site, and rent and maintain equipment for large energy and infrastructure projects, with our own transport fleet and bases in Riyadh, Dammam and Jeddah.": "ALL GOOD 电力建设是一家总部位于利雅得的工业贸易与工程服务集团。我们为大型能源和基础设施项目供应材料、开展现场施工，并提供设备租赁与维护，拥有自有运输车队，并在利雅得、达曼和吉达设有基地。",
    "Mission": "使命",
    "Long-term partnerships with world-class EPC contractors, supporting Saudi Arabia's energy and infrastructure development.": "与世界一流 EPC 总承包商建立长期合作，助力沙特能源与基础设施发展。",
    "Vision": "愿景",
    "To be the most trusted industrial trading and engineering service group in the Middle East, taking part in Saudi Vision 2030.": "成为中东最值得信赖的工业贸易与工程服务集团，深度参与沙特 2030 愿景。",
    "Integrity": "诚信",
    "Excellence": "卓越",
    "Innovation": "创新",
    "Win-Win": "共赢",
    "What we do": "业务范围",
    "Our five business units": "五大业务板块",
    "Everything a project needs, from one partner.": "项目所需，一站提供。",
    "Unit 01": "板块 01",
    "Unit 02": "板块 02",
    "Unit 03": "板块 03",
    "Unit 04": "板块 04",
    "Unit 05": "板块 05",
    "Electrical materials": "电气材料",
    "Exclusive agent of Bahra Electric, Saudi Arabia's largest local cable manufacturer. SEC-compliant.": "沙特最大本土电缆制造商 Bahra Electric 独家代理，产品符合 SEC 标准。",
    "Power & control cables": "电力与控制电缆",
    "Cable trays & conduits": "电缆桥架与线管",
    "Switchgear & distribution": "开关柜与配电",
    "Lighting & wiring devices": "照明与布线器件",
    "Instrumentation": "仪器仪表",
    "Communication & fiber optic": "通信与光纤",
    "Steel & metal fabrication": "钢结构与金属加工",
    "In-house fabrication for oil, chemical and power plants, to ASME, ASTM, DIN and GB standards.": "自有加工能力，服务石油、化工和电力工厂，执行 ASME、ASTM、DIN 和 GB 标准。",
    "Pipes, flanges & fittings": "管道、法兰与管件",
    "Industrial valves": "工业阀门",
    "Steel structures": "钢结构",
    "Fasteners & stud bolts": "紧固件与双头螺栓",
    "Embedded parts & anchor bolts": "预埋件与地脚螺栓",
    "Gaskets, plates & bars": "垫片、板材与棒材",
    "Engineering construction": "工程施工",
    "Professional site crews working to international standards, with a zero safety incident record.": "专业施工队伍执行国际标准，保持零安全事故记录。",
    "Waterproofing": "防水工程",
    "Anti-corrosion & insulation": "防腐与保温",
    "Scaffolding": "脚手架",
    "Pipeline installation": "管道安装",
    "Temporary camps": "临时营地",
    "Building materials": "建筑材料",
    "Equipment & site support": "设备与现场支持",
    "Agent for Cummins generators, Stamford alternators and Deep Sea controllers. Rental, maintenance and 24-hour response across the Kingdom.": "代理康明斯（Cummins）发电机组、斯坦福（Stamford）发电机和深海（Deep Sea）控制器，提供覆盖沙特全境的租赁、维护和 24 小时响应。",
    "Earth moving equipment": "土方设备",
    "Cranes & man lifts": "吊车与高空作业平台",
    "Generators": "发电机",
    "Welding equipment": "焊接设备",
    "Trucks & trailers": "卡车与挂车",
    "24/7 emergency response": "24 小时应急响应",
    "Local manufacturing": "本地制造",
    "Coming soon": "即将投产",
    "An automated cable tray factory supporting Saudi Vision 2030 and IKTVA local content. With Bahra Electric, one supplier for cable and tray.": "自动化电缆桥架工厂，响应沙特 2030 愿景与 IKTVA 本地化要求。与 Bahra Electric 协同，电缆和桥架一站供应。",
    "Trough & perforated trays": "槽式与托盘式桥架",
    "Ladder & wide-span trays": "梯级式与大跨距桥架",
    "Hot-dip galvanized steel": "热浸镀锌钢",
    "Stainless steel & aluminum": "不锈钢与铝合金",
    "Selected projects": "精选项目",
    "Wind power": "风电",
    "Solar power": "光伏",
    "Power plant": "电站",
    "Gas turbine": "燃机",
    "Giga-project": "超级项目",
    "Turaif Wind Power Project": "图赖夫风电项目",
    "Saidawi Solar Power Project": "赛达维光伏项目",
    "Riyadh Qassim CCGT": "利雅得卡西姆联合循环电站",
    "Wadi Solar Power Project": "瓦迪光伏项目",
    "PP12 Gas Turbine": "PP12 燃机项目",
    "Full HV/LV cable supply for PowerChina. On-time grid connection.": "为中国电建全面供应高低压电缆，按期并网。",
    "Complete cable and cable tray system for Energy China.": "为中国能建提供完整的电缆及桥架系统。",
    "Steel structures, pipes and flanges for PowerChina.": "为中国电建供应钢结构、管道和法兰。",
    "Complete steel structure package for Shandong Electric.": "为山东电建提供成套钢结构。",
    "View details": "查看详情",
    "Trusted by contractors, partners and the industry": "深受承包商、合作伙伴与行业信赖",
    "EPC partners": "EPC 合作伙伴",
    "Brand agencies": "品牌代理",
    "Standards": "标准认证",
    "Meet the team": "团队介绍",
    "The people behind your project": "为您的项目保驾护航",
    "Yu Peng Peng": "于鹏鹏",
    "Business contact": "业务联系人",
    "Quotations, supply enquiries, equipment rental and project partnerships.": "负责报价、供货咨询、设备租赁与项目合作。",
    "Team member name": "团队成员姓名",
    "Position": "职位",
    "Short biography: this person's background, experience and what they handle for clients.": "简介：成员背景、经验及负责的客户事务。",
    "Contact": "联系我们",
    "Let's talk about your project": "欢迎洽谈您的项目",
    "Phone": "电话",
    "WhatsApp": "WhatsApp",
    "WeChat": "微信",
    "WeChat ID": "微信号",
    "Email": "邮箱",
    "info@allgoodpower.com": "info@allgoodpower.com",
    "name@allgoodpower.com": "name@allgoodpower.com",
    "Head office": "总部",
    "Riyadh, Kingdom of Saudi Arabia": "沙特阿拉伯 利雅得",
    "Bases": "基地",
    "Dammam · Jeddah": "达曼 · 吉达",
    "Scan with WeChat to add us.": "微信扫码添加我们。",
    "Riyadh (head office)": "利雅得（总部）",
    "Dammam": "达曼",
    "Jeddah": "吉达",
    "Project site": "项目现场",
    "Order deliveries": "订单交付",
    "Location": "地点",
    "EPC": "EPC 总包",
    "Client / EPC": "业主 / EPC 总包",
    "Business unit": "业务板块",
    "Result": "成果",
    "Turaif, Saudi Arabia": "沙特阿拉伯 图赖夫",
    "Saudi Arabia": "沙特阿拉伯",
    "Riyadh & Qassim, Saudi Arabia": "沙特阿拉伯 利雅得与卡西姆",
    "Qiddiya, Riyadh, Saudi Arabia": "沙特阿拉伯 利雅得 齐迪亚",
    "PowerChina: Shandong Electric Power Construction Corp. No.3": "中国电建：山东电力建设第三工程有限公司",
    "Energy China: Hunan Electric Power Construction Co., Ltd.": "中国能建：湖南电力建设有限公司",
    "PowerChina": "中国电建",
    "Shandong Electric Power Construction Group": "山东电力建设集团",
    "Full supply of HV and LV wind power cables, compliant with SEC standards.": "全面供应符合 SEC 标准的风电高低压电缆。",
    "On-time grid connection, with quality certified by the contractor.": "按期并网，质量获总包方认可。",
    "Full cable and cable tray system, in trough and ladder types.": "完整的电缆及桥架系统，含槽式和梯级式桥架。",
    "One integrated cable-and-tray package; ALL GOOD became a strategic supplier for Energy China.": "电缆与桥架一体化解决方案；ALL GOOD 成为中国能建的战略供应商。",
    "Bulk supply of steel structural components for large gas turbine power plants: pipes, flanges and a full steel package.": "为大型燃机电站批量供应钢结构构件：管道、法兰及全套钢材。",
    "Delivered to a strict schedule and quality standard, leading to a long-term strategic partnership.": "严格按工期与质量交付，建立长期战略合作。",
    "Complete steel structure, plus the full series of flanges, pipe fittings, fasteners and embedded parts.": "成套钢结构，以及全系列法兰、管件、紧固件和预埋件。",
    "Full compliance with international quality standards and smooth project completion.": "完全符合国际质量标准，项目顺利完工。",
    "Expansion of the project camp: prefabricated buildings and steel structures for the cafeteria, activity room and staff dormitories.": "项目营地扩建：食堂、活动室和员工宿舍的装配式建筑与钢结构。",
    "ALL GOOD Power Construction · Riyadh, Kingdom of Saudi Arabia": "ALL GOOD 电力建设 · 沙特阿拉伯 利雅得",
    "ALL GOOD Power Construction is an industrial trading and engineering service group headquartered in Riyadh, supplying cables, steel structures, equipment and construction services to energy and infrastructure projects across Saudi Arabia.": "ALL GOOD 电力建设是一家总部位于利雅得的工业贸易与工程服务集团，为沙特各地能源与基础设施项目供应电缆、钢结构、设备并提供施工服务。",
    "ALL GOOD Power Construction home": "ALL GOOD 电力建设首页",
    "Open menu": "打开菜单",
    "Language": "语言",
    "The ALL GOOD team": "ALL GOOD 团队",
    "Previous photo": "上一张",
    "Next photo": "下一张",
    "Previous project": "上一个项目",
    "Next project": "下一个项目",
    "Energy China": "中国能建",
    "Shandong Electric Power Construction Corp. No.3": "山东电力建设第三工程有限公司",
    "Hunan Electric Power Construction": "湖南电力建设有限公司",
    "Bahra Electric": "Bahra Electric",
    "Cummins": "康明斯",
    "Stamford": "斯坦福",
    "Deep Sea": "深海",
    "Saudi Electricity Company (SEC)": "沙特电力公司（SEC）",
    "Saudi Aramco": "沙特阿美",
    "SABIC": "沙特基础工业公司（SABIC）",
    "ISO": "ISO",
    "ASME": "ASME",
    "ASTM": "ASTM",
    "Call Yu Peng Peng": "致电于鹏鹏",
    "WeChat QR code": "微信二维码",
    "ALL GOOD head office on Google Maps": "ALL GOOD 总部（谷歌地图）",
    "Business units": "业务板块",
    "Camp expansion built on site, with our own steel materials.": "现场完成营地扩建，并自供钢材。",
    "Engineering construction · Steel & metal fabrication": "工程施工 · 钢结构与金属加工",
    "Full-range steel structure materials for the camp buildings, compliant with ASME and ASTM standards.": "为营地建筑供应全系列钢结构材料，符合 ASME 和 ASTM 标准。",
    "Our role": "我方角色",
    "Our works on site": "现场施工",
    "Scope as supplier": "供货范围",
    "Supplier": "供应商",
    "We source, deliver and hand over materials and equipment to the project's contractors.": "为项目承包商采购、运送并交付材料和设备。",
    "@works-photos": "{x}：现场施工照片",
    "@works-photo": "{x}：现场施工，照片 {n}",
    "Client": "业主",
    "Qiddiya Delta B Office": "齐迪亚 Delta B 办公楼",
    "Qiddiya Delta B Office: architectural rendering": "齐迪亚 Delta B 办公楼：建筑效果图",
    "Qiddiya Delta B office, architectural rendering": "齐迪亚 Delta B 办公楼，建筑效果图",
    "Qiddiya Investment Company (QIC)": "齐迪亚投资公司（QIC）",
    "Turnkey steel-structure office for 200 staff: design, build and operate.": "200 人钢结构办公楼交钥匙工程：设计、建造与运维。",
    "As a supplier, as a contractor on site, and on some projects both.": "我们可作为供应商或现场承包商，部分项目两者兼任。",
    "Contractor": "承包商",
    "Contractor & Supplier": "承包商及供应商",
    "Scope as contractor": "施工范围",
    "Our own crews carry out works inside the project, as main contractor or subcontractor: construction, installation and site services.": "由自有队伍进场施工，担任总包或分包：建设、安装及现场服务。",
    "Turnkey design, construction and operation of a 200-staff steel-structure office.": "200 人钢结构办公楼的交钥匙设计、施工与运维。",
    "Close": "关闭",
    "@photos": "{x}照片",
    "@photo": "{x}：照片 {n}",
    "@site-photos": "{x}：项目现场照片",
    "@site-photo": "{x}：项目现场，照片 {n}",
    "@delivery-photos": "{x}：订单交付照片",
    "@delivery-photo": "{x}：订单交付，照片 {n}",
}

# image descriptions are built from a name plus a fixed ending
PATTERNS = [
    (r"^(.*): project site photos$", "@site-photos"),
    (r"^(.*): project site, photo (\d+)$", "@site-photo"),
    (r"^(.*): order delivery photos$", "@delivery-photos"),
    (r"^(.*): order delivery, photo (\d+)$", "@delivery-photo"),
    (r"^(.*): our works on site photos$", "@works-photos"),
    (r"^(.*): our works on site, photo (\d+)$", "@works-photo"),
    (r"^(.*), photo (\d+)$", "@photo"),
    (r"^(.*) photos$", "@photos"),
]

LANGS = {
    "ar": dict(file="ar.html", table=AR, attrs='lang="ar" dir="rtl"',
               font="family=IBM+Plex+Sans+Arabic:wght@400;600;700"),
    "zh-Hans": dict(file="zh.html", table=ZH, attrs='lang="zh-Hans"',
                    font="family=Noto+Sans+SC:wght@400;700;900"),
}


def build(code, cfg):
    table, missing = cfg["table"], set()

    def tr(text):
        key = html.unescape(text.strip())
        if not re.search("[A-Za-z]", key) or key == "width=device-width, initial-scale=1":
            return None
        if key in table:
            return table[key]
        for pat, tmpl in PATTERNS:
            m = re.match(pat, key)
            if m and html.unescape(m.group(1)) in table:
                n = m.group(2) if m.lastindex and m.lastindex > 1 else ""
                return table[tmpl].format(x=table[html.unescape(m.group(1))], n=n)
        missing.add(key)
        return None

    src = open("index.html", encoding="utf-8").read()
    # keep scripts, styles and comments untouched
    keep = []
    def stash(m):
        keep.append(m.group(0))
        return f"\x00{len(keep) - 1}\x00"
    out = re.sub(r"<!--.*?-->|<(script|style)[^>]*>.*?</\1>", stash, src, flags=re.S)

    def text_node(m):
        raw = m.group(1)
        t = tr(raw)
        if t is None:
            return m.group(0)
        lead = raw[: len(raw) - len(raw.lstrip())]
        trail = raw[len(raw.rstrip()):]
        return ">" + lead + html.escape(t, quote=False) + trail + "<"
    out = re.sub(r">([^<>]+)<", text_node, out)

    def attr(m):
        t = tr(m.group(2))
        return m.group(0) if t is None else f'{m.group(1)}="{html.escape(t)}"'
    out = re.sub(r'\b(alt|aria-label|title|content)="([^"]*)"', attr, out)

    out = re.sub(r"\x00(\d+)\x00", lambda m: keep[int(m.group(1))], out)
    out = out.replace('<html lang="en">', f"<html {cfg['attrs']}>", 1)
    out = out.replace("&family=Montserrat", f"&{cfg['font']}&family=Montserrat", 1)
    out = out.replace('aria-current="true">EN<', ">EN<", 1)
    out = re.sub(r'(<a href="%s"[^>]*?)>' % cfg["file"], r'\1 aria-current="true">', out, 1)
    if missing:
        print(f"{cfg['file']}: no translation for:", *sorted(missing), sep="\n  ")
        return False
    open(cfg["file"], "w", encoding="utf-8").write(out)
    print("wrote", cfg["file"])
    return True


ok = all([build(code, cfg) for code, cfg in LANGS.items()])
sys.exit(0 if ok else 1)
